all:
  hosts:
    silo6.sciencedata.dk:
      demo_string: "hello world, from silo6"
    silo7.sciencedata.dk:
      demo_string: "hello world, from silo7"
    silo8.sciencedata.dk:
      demo_string: "hello world, from silo8"
    kube.sciencedata.dk:
      demo_string: "hello world, from kube"
  children:
    testing:
      hosts:
        silo7.sciencedata.dk:
        silo8.sciencedata.dk:
    production:
      hosts:
        silo6.sciencedata.dk:
    sciencedata:
      hosts:
        silo6.sciencedata.dk:
        silo7.sciencedata.dk:
        silo8.sciencedata.dk:
    kubernetes:
      hosts:
        kube.sciencedata.dk:
